CREATE TABLE aml_user (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR2(100),
                          email VARCHAR2(100) UNIQUE,
                          password VARCHAR2(255)
);

CREATE TABLE aml_transaction (
                                 id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id NUMBER,
                                 amount NUMBER(10, 2),
                                 date_transaction DATE,
                                 suspicious_flag CHAR(1),
                                 FOREIGN KEY (user_id) REFERENCES aml_user(id)
);
